// import { Geist, Geist_Mono } from "next/font/google";
import { Alegreya } from "next/font/google";
import "./globals.css";
import "rsuite/dist/rsuite.min.css";
import NavProvider from "@/providers/nav-global-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const alegreya = Alegreya({
  subsets: ["latin"],
  weights: [400, 500, 700],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${alegreya.className} antialiased`}
      >
        <NavProvider>
        {children}
        </NavProvider>
      </body>
    </html>
  );
}
